apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: yesodotdevops.azurecr.io/halbana/ci_agent:0.1.0
        ports:
        - containerPort: 80  
        
        volumeMounts:
        - mountPath: /app/Yesodot/Unorganize
          name: images
        - mountPath: /app/Yesodot/Unorganize
          name: images
      
      volumes:
      - name: images
        azureFile:
          secretName: azure-volume
          shareName: devops/images
          readOnly: false
      - name: images
        azureFile:
          secretName: azure-volume
          shareName: devops/test
          readOnly: false